server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
    # creates the database automatically if it doesn't exist
    url: jdbc:mysql://localhost:3306/pizza_user_db?createDatabaseIfNotExist=true
    username: root
    password: jeeva123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  kafka:
    consumer:
      # Use ErrorHandlingDeserializer to catch and log serialization issues without crashing
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      # New group ID to skip "poison pill" records from previous failed runs
      group-id: user-group-v1
      auto-offset-reset: earliest
      properties:
        # Delegate the actual work to JsonDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.json.trusted.packages: "*"
        # Bridges the gap between the Auth-Service DTO and User-Service DTO
        spring.json.type.mapping: "com.pizza.auth_service.dto.UserRegistrationEvent:com.pizza.user_service.dto.UserRegistrationEvent"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true