server:
  port: 8084  # Distinct port for Payment Service

spring:
  application:
    name: payment-service

  # 1. Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/pizza_payment_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: jeeva123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # 2. Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092 # Use 'localhost:9092' if app runs in IDE. Change to 'kafka:29092' if app runs inside Docker container.
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# 3. Service Discovery Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# 4. Razorpay Credentials
razorpay:
  key:
    id: YOUR_RAZORPAY_KEY_ID
    secret: YOUR_RAZORPAY_KEY_SECRET