server:
  port: 8084  # Distinct port for Payment Service

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/pizza_payment_db?createDatabaseIfNotExist=true
    username: root
    password: jeeva123 # Replace with your MySQL password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Razorpay Credentials (Get these from your Razorpay Dashboard)
razorpay:
  key:
    id: YOUR_RAZORPAY_KEY_ID
    secret: YOUR_RAZORPAY_KEY_SECRET